/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.yakindu.analysis.example;

import hu.bme.mit.yakindu.analysis.IStatemachine;
import hu.bme.mit.yakindu.analysis.ITimerCallback;

public interface IExampleStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseKezd();
		
		public void raiseFeher();
		
		public void raiseBrown();
		
		public long getEgyikTime();
		
		public void setEgyikTime(long value);
		
		public long getLilaTime();
		
		public void setLilaTime(long value);
		
	}
	
	public SCInterface getSCInterface();
	
}
